---
- name: Install and configure Splunk Free
  hosts: splunk_server
  become: yes
  vars:
    splunk_filename: "splunk-9.4.1-e3bdab203ac8-linux-amd64.tgz"
    splunk_url: "https://download.splunk.com/products/splunk/releases/9.4.1/linux/splunk-9.4.1-e3bdab203ac8-linux-amd64.tgz"
    splunk_install_dir: /opt
    splunk_user: splunk
    splunk_home: "{{ splunk_install_dir }}/splunk"
  tasks:

    - name: Install dependencies
      apt:
        name: [wget, openssl]
        state: present
        update_cache: yes

    - name: Create splunk user
      user:
        name: "{{ splunk_user }}"
        shell: /bin/bash
        create_home: yes

    - name: Download Splunk tarball
      get_url:
        url: "{{ splunk_url }}"
        dest: "/tmp/{{ splunk_filename }}"
        mode: '0644'

    - name: Extract Splunk
      unarchive:
        src: "/tmp/{{ splunk_filename }}"
        dest: "{{ splunk_install_dir }}"
        remote_src: yes
        owner: "{{ splunk_user }}"
        group: "{{ splunk_user }}"

    - name: Generate random admin password using openssl
      shell: "openssl rand -base64 16"
      register: admin_password
      changed_when: false

    - name: Accept license and set admin password
      command: >
        {{ splunk_home }}/bin/splunk start --accept-license --answer-yes
        --no-prompt --seed-passwd "{{ admin_password.stdout }}"
      become_user: "{{ splunk_user }}"
      args:
        creates: "{{ splunk_home }}/ftr"

    - name: Enable Splunk to start at boot
      command: "{{ splunk_home }}/bin/splunk enable boot-start -user {{ splunk_user }}"
      become_user: root

    - name: Start Splunk
      command: "{{ splunk_home }}/bin/splunk start"
      become_user: "{{ splunk_user }}"

    - name: Print admin password
      debug:
        msg: "Splunk Admin Passwort: {{ admin_password.stdout }}"
