- name: Install and configure Splunk Free
  hosts: splunk_server
  become: yes
  vars:
    splunk_filename: "splunk-9.4.1-e3bdab203ac8-linux-amd64.tgz"
    splunk_url: "https://download.splunk.com/products/splunk/releases/9.4.1/linux/splunk-9.4.1-e3bdab203ac8-linux-amd64.tgz"
    splunk_install_dir: /opt
    splunk_user: splunk
    splunk_home: "{{ splunk_install_dir }}/splunk"
    splunk_admin_user: admin

  tasks:

    - name: Check if Splunk is already installed
      stat:
        path: "{{ splunk_home }}/bin/splunk"
      register: splunk_installed

    - name: Abort if Splunk is already installed
      fail:
        msg: "Splunk scheint bereits installiert zu sein unter {{ splunk_home }}. Installation wird abgebrochen."
      when: splunk_installed.stat.exists

    - name: Install dependencies
      apt:
        name: [wget, openssl]
        state: present
        update_cache: yes

    - name: Create splunk user
      user:
        name: "{{ splunk_user }}"
        shell: /bin/bash
        create_home: yes

    - name: Download Splunk tarball
      get_url:
        url: "{{ splunk_url }}"
        dest: "/tmp/{{ splunk_filename }}"
        mode: '0644'

    - name: Extract Splunk
      unarchive:
        src: "/tmp/{{ splunk_filename }}"
        dest: "{{ splunk_install_dir }}"
        remote_src: yes

    - name: Fix permissions after extract
      file:
        path: "{{ splunk_home }}"
        state: directory
        recurse: yes
        owner: "{{ splunk_user }}"
        group: "{{ splunk_user }}"

    - name: Generate random admin password using openssl
      shell: "openssl rand -base64 16"
      register: admin_password
      changed_when: false

    - name: Create user-seed.conf to preset admin credentials
      copy:
        dest: "{{ splunk_home }}/etc/system/local/user-seed.conf"
        content: |
          [user_info]
          USERNAME = {{ splunk_admin_user }}
          PASSWORD = {{ admin_password.stdout }}
        owner: "{{ splunk_user }}"
        group: "{{ splunk_user }}"
        mode: '0600'

    - name: Accept license and start Splunk (first run)
      command: "{{ splunk_home }}/bin/splunk start --accept-license"
      become_user: "{{ splunk_user }}"
      args:
        creates: "{{ splunk_home }}/ftr"

    - name: Enable Splunk to start at boot
      command: "{{ splunk_home }}/bin/splunk enable boot-start --accept-license"
      become_user: root

    - name: Start Splunk service
      command: "{{ splunk_home }}/bin/splunk start"
      become_user: "{{ splunk_user }}"

    - name: Print Splunk Admin credentials
      debug:
        msg: |
          Splunk Admin Zugang:
            Username: {{ splunk_admin_user }}
            Passwort: {{ admin_password.stdout }}
