---
- name: Install sudo on Debian and Ubuntu systems
  hosts: all  # Hier die Gruppe von Hosts angeben
  tasks:
    - name: Check if sudo is already installed
      command: which sudo
      register: result
      ignore_errors: yes  # Ignoriere Fehler, wenn sudo nicht installiert ist

    - name: Install sudo if it is not already installed (without sudo)
      # Wenn sudo nicht verfügbar ist, verwenden wir `apt` als root
      apt:
        name: sudo
        state: present
      when: result.rc != 0  # Installiere sudo nur, wenn es nicht bereits vorhanden ist
      become: false  # Hier stellen wir sicher, dass wir ohne sudo installieren, weil sudo fehlt

