---
- name: Splunk Universal Forwarder entfernen
  hosts: all
  become: yes
  tasks:

    - name: Dienst stoppen (systemd)
      ansible.builtin.systemd:
        name: splunkforwarder
        state: stopped
        enabled: no
      ignore_errors: true

    - name: Dienst stoppen (Fallback, splunk CLI)
      command: /opt/splunkforwarder/bin/splunk stop
      args:
        warn: false
      ignore_errors: true

    - name: Entferne Systemd-Service-Datei (falls vorhanden)
      file:
        path: /etc/systemd/system/splunkforwarder.service
        state: absent

    - name: Entferne Splunk-Installationsverzeichnis
      file:
        path: /opt/splunkforwarder
        state: absent

    - name: Entferne Splunk-Logs und Konfigurationen (falls getrennt)
      file:
        path: /var/log/splunk
        state: absent

    - name: Entferne ggf. alte Init-Skripte (SysV)
      file:
        path: /etc/init.d/splunk
        state: absent

    - name: Systemd Daemon neuladen
      ansible.builtin.systemd:
        daemon_reload: yes
