---
- name: Install and configure Splunk Universal Forwarder
  hosts: agents
  become: yes

  vars:
    forwarder_version: "9.4.1"
    forwarder_build: "e3bdab203ac8"
    splunk_server_ip: "172.16.2.80"
    splunk_server_port: 9997
    splunk_admin_user: admin
    splunk_admin_password: "{{ lookup('env', 'SPLUNK_PASSWORD') }}"
    splunk_install_dir: /opt
    splunk_home: "{{ splunk_install_dir }}/splunkforwarder"
    splunk_filename: "splunkforwarder-{{ forwarder_version }}-{{ forwarder_build }}-linux-amd64.tgz"
    splunk_url: "https://download.splunk.com/products/universalforwarder/releases/{{ forwarder_version }}/linux/{{ splunk_filename }}"
    log_index: "debian_logs"

  tasks:
    - name: Ensure password env var is set
      fail:
        msg: "Environment variable SPLUNK_PASSWORD is not set!"
      when: splunk_admin_password == ""

    - name: Check if Splunk Forwarder is already installed
      stat:
        path: "{{ splunk_home }}/bin/splunk"
      register: splunk_forwarder_installed

    - name: Skip installation if Splunk Forwarder is already installed
      debug:
        msg: "Splunk Forwarder is already installed. Skipping installation."
      when: splunk_forwarder_installed.stat.exists

    - name: Stop Splunk Forwarder if running
      command: "{{ splunk_home }}/bin/splunk stop"
      when: splunk_forwarder_installed.stat.exists

    - name: Download Splunk Forwarder (preferred method)
      get_url:
        url: "{{ splunk_url }}"
        dest: "/tmp/{{ splunk_filename }}"
        mode: '0644'
        validate_certs: no
      register: download_result
      failed_when: false
      when: not splunk_forwarder_installed.stat.exists

    - name: Download Splunk Forwarder (fallback via curl)
      shell: |
        curl -fSL "{{ splunk_url }}" -o "/tmp/{{ splunk_filename }}"
      args:
        creates: "/tmp/{{ splunk_filename }}"
      when: not splunk_forwarder_installed.stat.exists and (download_result is failed or download_result.failed)

    - name: Extract Splunk Forwarder
      unarchive:
        src: "/tmp/{{ splunk_filename }}"
        dest: "{{ splunk_install_dir }}"
        remote_src: yes
      when: not splunk_forwarder_installed.stat.exists

    - name: Create user-seed.conf to preset admin credentials
      copy:
        dest: "{{ splunk_home }}/etc/system/local/user-seed.conf"
        content: |
          [user_info]
          USERNAME = {{ splunk_admin_user }}
          PASSWORD = {{ splunk_admin_password }}
        mode: '0600'
      when: not splunk_forwarder_installed.stat.exists

    - name: Accept license and start Splunk Forwarder (first run)
      command: "{{ splunk_home }}/bin/splunk start --accept-license"
      args:
        creates: "{{ splunk_home }}/ftr"
      when: not splunk_forwarder_installed.stat.exists

    - name: Check if SplunkForwarder systemd unit already exists
      stat:
        path: /etc/systemd/system/SplunkForwarder.service
      register: forwarder_service_file

    - name: Remove existing SplunkForwarder systemd unit if present
      command: "{{ splunk_home }}/bin/splunk disable boot-start"
      when: forwarder_service_file.stat.exists

    - name: Enable Splunk Forwarder to start on boot (as root)
      command: "{{ splunk_home }}/bin/splunk enable boot-start --accept-license -user root"
      when: not splunk_forwarder_installed.stat.exists

    - name: Add Splunk Server as Forward Target
      command: >
        {{ splunk_home }}/bin/splunk add forward-server {{ splunk_server_ip }}:{{ splunk_server_port }}
        -auth {{ splunk_admin_user }}:{{ splunk_admin_password }}
      when: not splunk_forwarder_installed.stat.exists

    - name: Monitor system logs
      command: >
        {{ splunk_home }}/bin/splunk add monitor /var/log
        -index {{ log_index }}
        -auth {{ splunk_admin_user }}:{{ splunk_admin_password }}
      when: not splunk_forwarder_installed.stat.exists

    - name: Restart Splunk Forwarder
      command: "{{ splunk_home }}/bin/splunk restart"
      when: not splunk_forwarder_installed.stat.exists
