---
- name: Install and configure Splunk Universal Forwarder on Debian/Ubuntu
  hosts: all
  become: true

  vars:
    splunk_forwarder_url: "https://download.splunk.com/products/universalforwarder/releases/9.1.2/linux/splunkforwarder-9.1.2-b6b9c8185839-linux-2.6-amd64.deb"
    splunk_deb: "/tmp/splunkforwarder.deb"
    splunk_admin_password: "Jegi2012*"
    splunk_bin_path: "/opt/splunkforwarder/bin/splunk"
    inputs_conf: "/opt/splunkforwarder/etc/system/local/inputs.conf"
    outputs_conf: "/opt/splunkforwarder/etc/system/local/outputs.conf"

  pre_tasks:
    - name: Check if Splunk is already installed
      stat:
        path: "{{ splunk_bin_path }}"
      register: splunk_bin

    - name: Check if monitor config exists
      stat:
        path: "{{ inputs_conf }}"
      register: splunk_inputs_conf

    - name: Check if forward-server config exists
      stat:
        path: "{{ outputs_conf }}"
      register: splunk_outputs_conf

  tasks:
    - name: Ensure wget is installed
      apt:
        name: wget
        state: present
        update_cache: yes

    - name: Download Splunk Forwarder using wget
      shell: "wget -O {{ splunk_deb }} {{ splunk_forwarder_url }}"
      args:
        creates: "{{ splunk_deb }}"
      when: not splunk_bin.stat.exists

    - name: Install Splunk Universal Forwarder
      apt:
        deb: "{{ splunk_deb }}"
      when: not splunk_bin.stat.exists

    - name: Create splunk user
      user:
        name: splunk
        shell: /bin/bash
        create_home: yes
      when: not splunk_bin.stat.exists

    - name: Accept Splunk license and set admin password
      command: "{{ splunk_bin_path }} start --accept-license --answer-yes --no-prompt --seed-passwd '{{ splunk_admin_password }}'"
      args:
        creates: /opt/splunkforwarder/etc/passwd
      no_log: true
      when: not splunk_bin.stat.exists

    - name: Enable boot-start for splunk user
      command: "{{ splunk_bin_path }} enable boot-start -user splunk"
      when: not splunk_bin.stat.exists

    - name: Add monitor for all logs in /var/log
      command: "{{ splunk_bin_path }} add monitor /var/log -auth alessio@binz.family:'{{ splunk_admin_password }}'"
      no_log: true
      when: not splunk_inputs_conf.stat.exists

    - name: Configure forward-server
      command: "{{ splunk_bin_path }} add forward-server 172.16.2.80:9997 -auth alessio@binz.family:'{{ splunk_admin_password }}'"
      no_log: true
      when: not splunk_outputs_conf.stat.exists

    - name: Restart Splunk Forwarder via systemd
      systemd:
        name: SplunkForwarder
        state: restarted
        enabled: true
      when: splunk_bin.stat.exists
