---
- name: Install and configure Splunk Universal Forwarder on Debian/Ubuntu
  hosts: all
  become: true

  vars:
    splunk_forwarder_url: "https://download.splunk.com/products/universalforwarder/releases/9.1.2/linux/splunkforwarder-9.1.2-b6b9c8185839-linux-2.6-amd64.deb"
    splunk_deb: "/tmp/splunkforwarder.deb"
    splunk_admin_password: "{{ lookup('env', 'SPLUNK_PASSWORD') }}" # optional override

  tasks:

    - name: Install required packages
      apt:
        name: wget
        state: present
        update_cache: yes

    - name: Download Splunk Universal Forwarder
      get_url:
        url: "{{ splunk_forwarder_url }}"
        dest: "{{ splunk_deb }}"
        mode: '0644'

    - name: Install Splunk Universal Forwarder
      apt:
        deb: "{{ splunk_deb }}"

    - name: Accept Splunk license and set admin password
      command: /opt/splunkforwarder/bin/splunk start --accept-license --answer-yes --no-prompt --seed-passwd "{{ splunk_admin_password }}"
      args:
        creates: /opt/splunkforwarder/etc/passwd

    - name: Enable boot-start
      command: /opt/splunkforwarder/bin/splunk enable boot-start -user splunk

    - name: Add monitor for all logs in /var/log
      command: /opt/splunkforwarder/bin/splunk add monitor /var/log -auth admin:"{{ splunk_admin_password }}"
      args:
        creates: /opt/splunkforwarder/etc/system/local/inputs.conf

    - name: Configure forward-server
      command: /opt/splunkforwarder/bin/splunk add forward-server 172.16.2.80:9997 -auth admin:"{{ splunk_admin_password }}"
      args:
        creates: /opt/splunkforwarder/etc/system/local/outputs.conf

    - name: Restart Splunk Forwarder
      command: /opt/splunkforwarder/bin/splunk restart
