- name: Install and configure Splunk Universal Forwarder
  hosts: agents
  become: yes
  vars:
    forwarder_version: "9.4.1"
    forwarder_build: "e3bdab203ac8"
    splunk_server_ip: "172.16.2.80"
    splunk_server_port: 9997
    splunk_admin_user: admin
    splunk_admin_password: "{{ lookup('env', 'SPLUNK_PASSWORD') }}"
    splunk_install_dir: /opt
    splunk_home: "{{ splunk_install_dir }}/splunkforwarder"
    splunk_filename: "splunkforwarder-9.4.1-e3bdab203ac8-linux-amd64.tgz"
    splunk_url: "https://download.splunk.com/products/universalforwarder/releases/9.4.1/linux/{{ splunk_filename }}"

  tasks:
    - name: Ensure password env var is set
      fail:
        msg: "Environment variable SPLUNK_PASSWORD is not set!"
      when: splunk_admin_password == ""

    - name: Download Splunk Forwarder
      get_url:
        url: "{{ splunk_url }}"
        dest: "/tmp/{{ splunk_filename }}"
        mode: '0644'

    - name: Extract Splunk Forwarder
      unarchive:
        src: "/tmp/{{ splunk_filename }}"
        dest: "{{ splunk_install_dir }}"
        remote_src: yes

    - name: Create user-seed.conf to preset admin credentials
      copy:
        dest: "{{ splunk_home }}/etc/system/local/user-seed.conf"
        content: |
          [user_info]
          USERNAME = {{ splunk_admin_user }}
          PASSWORD = {{ splunk_admin_password }}
        mode: '0600'

    - name: Accept license and start Splunk Forwarder (first run)
      command: "{{ splunk_home }}/bin/splunk start --accept-license"
      args:
        creates: "{{ splunk_home }}/ftr"

    - name: Check if SplunkForwarder systemd unit already exists
      stat:
        path: /etc/systemd/system/SplunkForwarder.service
      register: forwarder_service_file

    - name: Remove existing SplunkForwarder systemd unit if present
      command: "{{ splunk_home }}/bin/splunk disable boot-start"
      when: forwarder_service_file.stat.exists

    - name: Enable Splunk Forwarder to start on boot (as root)
      command: "{{ splunk_home }}/bin/splunk enable boot-start --accept-license -user root"

    - name: Add Splunk Server as Forward Target
      command: >
        {{ splunk_home }}/bin/splunk add forward-server {{ splunk_server_ip }}:{{ splunk_server_port }}
        -auth {{ splunk_admin_user }}:{{ splunk_admin_password }}

    - name: Monitor system logs
      command: >
        {{ splunk_home }}/bin/splunk add monitor /var/log
        -auth {{ splunk_admin_user }}:{{ splunk_admin_password }}

    - name: Restart Splunk Forwarder
      command: "{{ splunk_home }}/bin/splunk restart"
