---
- name: Install and configure Splunk Universal Forwarder on Debian/Ubuntu
  hosts: all
  become: true

  vars:
    splunk_forwarder_url: "https://download.splunk.com/products/universalforwarder/releases/9.1.2/linux/splunkforwarder-9.1.2-b6b9c8185839-linux-2.6-amd64.deb"
    splunk_deb: "/tmp/splunkforwarder.deb"
    splunk_admin_user: "alessio@binz.family"
    splunk_admin_password: "Jegi2012*"
    splunk_bin_path: "/opt/splunkforwarder/bin/splunk"
    splunk_version_file: "/opt/splunkforwarder/etc/splunk.version"
    inputs_conf: "/opt/splunkforwarder/etc/system/local/inputs.conf"
    outputs_conf: "/opt/splunkforwarder/etc/system/local/outputs.conf"

  pre_tasks:
    - name: Check if Splunk is installed (via version file)
      stat:
        path: "{{ splunk_version_file }}"
      register: splunk_installed

    - name: Check if monitor config exists
      stat:
        path: "{{ inputs_conf }}"
      register: splunk_inputs_conf

    - name: Check if forward-server config exists
      stat:
        path: "{{ outputs_conf }}"
      register: splunk_outputs_conf

    - name: Check if DEB file exists (after download)
      stat:
        path: "{{ splunk_deb }}"
      register: splunk_deb_file

  tasks:
    - name: Ensure wget is installed
      apt:
        name: wget
        state: present
        update_cache: yes

    - name: Download Splunk Forwarder using wget
      shell: "wget -O {{ splunk_deb }} {{ splunk_forwarder_url }}"
      args:
        creates: "{{ splunk_deb }}"
      when: not splunk_installed.stat.exists

    - name: Install or re-install Splunk Forwarder if needed
      apt:
        deb: "{{ splunk_deb }}"
        force: yes
      when: not splunk_installed.stat.exists and splunk_deb_file.stat.exists

    - name: Recheck if Splunk is now installed
      stat:
        path: "{{ splunk_bin_path }}"
      register: splunk_bin

    - name: Create splunk user
      user:
        name: splunk
        shell: /bin/bash
        create_home: yes
      when: splunk_bin.stat.exists

    - name: Check if Splunk is already running
      shell: pgrep -f splunkd
      register: splunk_running
      ignore_errors: true
      changed_when: false

    - name: Stop running Splunk instance (avoid port conflict)
      shell: "{{ splunk_bin_path }} stop"
      when: splunk_running.rc == 0
      ignore_errors: true

    - name: Disable legacy init.d boot-start if present
      command: "{{ splunk_bin_path }} disable boot-start"
      when: splunk_running.rc == 0
      ignore_errors: true

    - name: Accept Splunk license and set admin password
      command: "{{ splunk_bin_path }} start --accept-license --answer-yes --no-prompt --seed-passwd '{{ splunk_admin_password }}'"
      args:
        creates: /opt/splunkforwarder/etc/passwd
      when: splunk_running.rc != 0 and splunk_bin.stat.exists
      register: splunk_start_result

    - name: Debug splunk start result
      debug:
        var: splunk_start_result

    - name: Enable boot-start for splunk user
      command: "{{ splunk_bin_path }} enable boot-start -user splunk"
      when: splunk_bin.stat.exists

    - name: Add monitor for all logs in /var/log
      command: "{{ splunk_bin_path }} add monitor /var/log -auth '{{ splunk_admin_user }}:{{ splunk_admin_password }}'"
      when: not splunk_inputs_conf.stat.exists and splunk_bin.stat.exists

    - name: Configure forward-server
      command: "{{ splunk_bin_path }} add forward-server 172.16.2.80:9997 -auth '{{ splunk_admin_user }}:{{ splunk_admin_password }}'"
      when: not splunk_outputs_conf.stat.exists and splunk_bin.stat.exists

    - name: Restart Splunk Forwarder via systemd
      systemd:
        name: SplunkForwarder
        state: restarted
        enabled: true
      when: splunk_bin.stat.exists
